### ISSUE TITLE
[Discussion] `data-test` property on components

### ISSUE THREAD

**Issue by aDogCalledSpot** [patternfly-yew/patternfly-yew#106]
For end-to-end testing, there needs to be a good way to select a component. I think the best way to do this would be to add a `data-test` property to components.

This means in particular that in components that use composition, there should be meaningful names given to the `data-test` attribute.

**Comment by ctron** [comment]
Here: https://www.patternfly.org/developer-resources/open-ui-automation/

**Comment by aDogCalledSpot** [comment]
That is more than sufficient :sweat_smile: 

Conforming to this for components seems simple enough. `Page` and `Page-Safe` need to be done by users.

I suggest we have a static counter for the ouia-ids and a function to get the next ID and then we just add a prefix to each component. Should be simple enough.

**Comment by ctron** [comment]
Yes, the default could be a static counter.

> Should be simple enough.

Famous last words :rofl: 

Maybe `Page` (and others) could somehow be patternfly independent (dedicated crate :wink:) … but maybe also first start slow and then see what makes sense.
