### ISSUE TITLE
Rethink keys in tables

### ISSUE THREAD

**Issue by aDogCalledSpot** [patternfly-yew/patternfly-yew#132]
`TableModel` has a generic `Key` type that can be used for supplying better keys but `MemoizedTableModel` and `UseStateTableModel` simply assign `usize` and use the index in the entry vector.

This causes issues for when the data changes as the indices don't match the data anymore.
One example is if you render a cell with state inside, the state will actually be cached from the entry that was previously in that position leading to some surprising behaviour.

Since keys should really always be used for lists, I would propose letting the user assign keys and I've come up with two options that would work.

### Option 1: Get the key from a `Option<Callback<EntryType, KeyType>>` 

which is called on every row. If no callback is specified, then we can fall back to using the index.
The good thing about this approach is that it wouldn't even be a breaking change.

### Option 2: Get the key from a function in `TableEntryRenderer`

This would be a breaking change but it would force users to come up with proper keys and is a lot nicer to read in the code.

**Comment by ctron** [comment]
I agree that the whole table model idea needs a revamp. I would be afraid of just replacing it with something completely new.

If we can improve the current model (without any drawbacks), then let's to it. Otherwise, maybe it is time for "Tables Next", and keep the current implementation until the new one is good/stable enough.

**Comment by aDogCalledSpot** [comment]
If there's a good chance that we're deprecating the current Table implementation then I would just go with Option 1 here for stability and we should make a separate issue for discussing requirements for Tables Next and then see how that aligns with the current implementation.

**Comment by aDogCalledSpot** [comment]
The changes would actually have to be made at the very least in `MemoizedTableModel` and `UseStateTabelModel` or maybe even in `TableModel` itself. These changes would be very much breaking so I'm going to close this as won't fix and rather discuss TableNext.
