### ISSUE TITLE
Page Masthead and horizontal navigation

### ISSUE THREAD

**Issue by marcopio72** [patternfly-yew/patternfly-yew#141]
I would have liked a horizontal navigation page as described in Patternfly but I see that I can't eliminate the bars button.
From what I could see in the code there is no way to do this with the Page component. Or is there a way?

Marco

**Comment by ctron** [comment]
Maybe not right now. But if you can come up with a PR, I would be happy to merge that.

**Comment by marcopio72** [comment]
Yes, you would like to do it, but it would be the first PR ever. I have already made the change to my local copy.
I tried to create the PR but Github asks me to select a branch and I don't know which one is the right one, can you give me a tip?

**Comment by ctron** [comment]
`main` would be the correct branch.

**Comment by marcopio72** [comment]
Sorry for basic question. After click on "New Pull Request" a page "Comparing changes" appear where the button "Create Pull Request" is disabled. On the top left there are 2 selectors that show "base:main" and "compare:main". If I choose main the button "Create Pull Reqest" disappears and a message tells "There is nothing to compare".
For sure I miss some fundamental point. There are some operation to do before this step?

**Comment by ctron** [comment]
The typical process would be:

* Fork the repo (into your own account)
* Create a new (local) branch
* Make local changes
* `git add`, `git commit`, `git push`
* Then create a PR, from your branch to `patternfly-yew`'s `main` branch
