### ISSUE TITLE
Gallery: weird behavior w.r.t. scroll state / re-rendering?

### ISSUE THREAD

**Issue by antifuchs** [patternfly-yew/patternfly-yew#148]
I'm trying to make an infinitely-scrolling gallery, of this kind of shape:

```rust
use patternfly_yew::prelude::*;
use yew::prelude::*;

#[derive(Properties, PartialEq, Clone, Debug)]
pub struct GalleryTestProps {}

#[function_component(GalleryTest)]
pub fn gallery_test(GalleryTestProps {}: &GalleryTestProps) -> Html {
    let items = use_state(|| 50);
    let add_items = Callback::from({
        let items = items.clone();
        move |_| {
            items.set(*items + 50);
        }
    });
    html! {
        <>
            <Gallery>
                { for (0..(*items)).map(|number|
                    html!{<ExampleItem key={number} {number}/>}) }
            </Gallery>
            <Button onclick={add_items}>{ "moar" }</Button>
        </>
    }
}

#[derive(Properties, PartialEq, Clone, Debug)]
struct ExampleItemProps {
    number: usize,
}

#[function_component(ExampleItem)]
fn example_item(ExampleItemProps { number }: &ExampleItemProps) -> Html {
    tracing::info!(?number, "rendering");
    html! {
        <Card>
            <CardTitle>{ number }</CardTitle>
            { "This is item " }
            { number }
        </Card>
    }
}
```

(added to a page using `<GalleryTest />`)

Clicking the button adds 50 more items to the gallery, but two unexpected things happen: 
* I was expecting the browser's scroll state to be preserved at the position it was before clicking the button; it remains glued at the bottom, though.
* Every `ExampleItem` gets re-rendered, as though the gallery was emptied out and recreated from scratch.

**Comment by ctron** [comment]
`use_state` does not persist the state to any browser store. So when you navigate away and back, that state will initialize to its default again. You can use something like [`use_page_state`](https://docs.rs/yew-more-hooks/latest/yew_more_hooks/hooks/page_state/index.html) for that.

I am not sure where the re-rendering issue is coming from. To my understanding, using the key should prevent that. It might be that re-creating the content in the `for` loop causes that. You might want to try using `use_memo` with the `number` as argument and create the content inside of that. That should only re-create the list when the `number` changes.

**Comment by antifuchs** [comment]
I'm not worried at all about navigating away - users expect to get only the first batch of elements whenever they navigate there (but thanks for letting me know about `use_page_state` regardless).

That the content is deleted and re-created is exactly what I think is happening here; not sure I can change that by doing anything to the way the page is built (can't stop using a for loop, or changing the list of items to render). I'm looking into making some changes to the Gallery element that might help (it does create container `div`s that don't have a key, for one).

**Comment by antifuchs** [comment]
Quick update: Yep, it's because the containing element `div`s created by the Gallery don't have a key on them.

I made a PR fixing the behavior; it does require changing the wrapper logic to use the virtual DOM directly, instead of the html! macro. I hope that's ok.
