### ISSUE TITLE
Hover effects for clickable Cards

### ISSUE THREAD

**Issue by aDogCalledSpot** [patternfly-yew/patternfly-yew#71]
You can currently create a click callback on cards with the `onclick` prop. However, it isn't communicated to the user. The Patternfly docs show that the cards are dimmed when hovering them and that the cursor becomes a pointer.

I tried adding `pf-m-clickable` to the classes but that doesn't seem to do anything by itself.

Am using `pf-m-selectable-raised` as a workaround for now.

**Comment by ctron** [comment]
IIRC there had been some recent changes around cards. Maybe that's the cause. But I didn't check into it.
