### ISSUE TITLE
`UseStateHandle` created outside of a backdrop does not trigger a rerender inside the backdrop

### ISSUE THREAD

**Issue by aDogCalledSpot** [patternfly-yew/patternfly-yew#76]
I want to fetch data from the backend in a component. Pressing a button inside the component will open a backdrop which shows some more of the fetched data.

Ideally, I would like to have a `UseStateHandle` for the data, so I can check in the backdrop if all the data is already loaded.

However, once the data is there, it only reloads the data in the outside component (which you can sort of see in the background) and the component inside backdrop doesn't change.

Closing and reopening the backdrop view shows the correct data.

You can view a minimal example [here](https://gist.github.com/aDogCalledSpot/95bdb9945343a746f88b92b2b8f2d6b4).

**Comment by ctron** [comment]
Yea, I am not sure it is supposed to work that way :) I also don't think it is specific to PatternFly Yew.

The way to pass information from a parent component to a child component (and back) over multiple levels are "contexts". Alternatively, if the data is more local to the modal, then use the state in the modal.

For fetching data from the backend, I tend to use the `use_async*` hooks from either `yew-hooks` or `yew-more-hooks`.

**Comment by aDogCalledSpot** [comment]
I see. Thanks for the input.

The `use_async` hook looks interesting. I've just been doing it with `yew::platform::spawn_local` but this seems more elegant.
