### ISSUE TITLE
Release 0.5.0

### ISSUE THREAD

**Issue by ctron** [patternfly-yew/patternfly-yew#90]
Tracking issue for ToDo's before a 0.5.0 release … and I come up empty.

So time to speak up now!

**Comment by aDogCalledSpot** [comment]
I don't have anything to add. I would add the SearchInput in the next release, then it can be rolled out across the other components such as Dropdown gradually until the next big release.

**Comment by ctron** [comment]
We can also do 0.5.x releases, if we don't break APIs.

**Comment by ctron** [comment]
And it's released.
